osx_image: xcode10.1
language: objective-c

cache: cocoapods
podfile: Example/Podfile

before_install:
- gem install cocoapods
- pod install --repo-update --project-directory=Example

before_script:
  - set -o pipefail

script:
- xcodebuild clean build test
     -workspace Example/RxApolloClient.xcworkspace 
     -scheme RxApolloClient-Example 
     -sdk iphonesimulator
     -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.0'
     -configuration Debug
     -enableCodeCoverage YES
     CODE_SIGNING_REQUIRED=NO | xcpretty